
##########################
#
# use cases
# 
#########################

[robert-1]
type = "query"
doc = "Images Acquired by Pre-computed relationship between Images and Tile for tile=SN-X1_C16"
oracle_time = 0.29
query = """
SELECT fai.filename AS filename,
       fai.path AS PATH,
       fai.compression AS compression,
       i.band AS band,
       i.expnum AS expnum,
       i.ccdnum AS ccdnum,
       i.rac1 AS rac1,
       i.rac2 AS rac2,
       i.rac3 AS rac3,
       i.rac4 AS rac4,
       i.decc1 AS decc1,
       i.decc2 AS decc2,
       i.decc3 AS decc3,
       i.decc4 AS decc4
FROM image i,
     file_archive_info fai,
     proctag t,
     Y6DEEP_IMAGE_TO_TILE y
WHERE t.tag='Y6DEEP_X1_CT_INPUT'
  AND t.pfw_attempt_id=i.pfw_attempt_id
  AND i.filetype='red_immask'
  AND i.filename=fai.filename
  AND fai.archive_name='desar2home'
  AND i.filename=y.filename
  AND y.tilename='SN-X1_C16'
"""




[Robert-2]
type = "query" 
doc = "Executing query to obtain ZEROPOINTs corresponding to the red_immasked images"
oracle_time = 2.13 
query = """
SELECT gtt.filename AS filename,
       z.mag_zero AS mag_zero,
       i.expnum AS expnum,
       i.ccdnum AS ccdnum
FROM image i,
     gtt_filename gtt,
          zeropoint z
WHERE i.filename=gtt.filename
  AND z.imagename=i.filename
  AND z.mag_zero>-100.
  AND z.source='FGCM'
  AND z.version='y6a1_v2.1'
  AND z.flag<16
"""

[Robert-3]
type="query"
doc = "Executing query to obtain SECONDARY ZPTs corresponding to the red_immasked images"
oracle_time = 2.13
query = """
SELECT gtt.filename AS filename,
       z.mag_zero AS mag_zero,
       i.expnum AS expnum,
       i.ccdnum AS ccdnum
FROM image i,
     gtt.filename gtt,
          zeropoint z
WHERE i.filename=gtt.filename
  AND z.imagename=i.filename
  AND z.mag_zero>-100.
  AND z.source='NIRTEST'
  AND z.version='v8'
  AND z.flag<16
"""

[Robert-4]
type = "query"
doc = "query to remove blacklisted images"
oracle_time = 2.18
query = """
SELECT gtt.filename AS filename,
       i.expnum AS expnum,
       i.ccdnum AS ccdnum
FROM image i,
     gtt_filename gtt
WHERE i.filename=gtt.filename
  AND NOT EXISTS
    (SELECT bl.reason
     FROM Y6A1_EXCLUDE_LIST bl
     WHERE bl.expnum=i.expnum
       AND bl.ccdnum=i.ccdnum)
"""

[Robert-5]
type = "query"
doc = "Executing query to obtain red_bkg images corresponding to the red_immasked images" 
oracle_time = 2.61
query = """
SELECT i.filename AS redfile,
       fai.filename AS filename,
       fai.path AS PATH,
       fai.compression AS compression,
       k.band  AS band,
       k.expnum AS expnum,
       k.ccdnum AS ccdnum
FROM image i,
     image k,
     file_archive_info fai,
     GTT_FILENAME gtt
WHERE i.filename=gtt.filename
  AND i.pfw_attempt_id=k.pfw_attempt_id
  AND k.filetype='red_bkg'
  AND i.ccdnum=k.ccdnum
  AND k.filename=fai.filename
  AND fai.archive_name='desar2home'
"""

[Robert-6] 
type = "query"
oracle_time = -1
doc = "obtain segmentation map images corresponding to the red_immasked images"
query = """
SELECT i.filename AS redfile,
fai.filename AS filename,
fai.path AS PATH,
fai.compression AS compression,
m.band  AS band,
m.expnum AS expnum,
m.ccdnum AS ccdnum
FROM image i,
     miscfile m,
     file_archive_info fai,
     GTT_FILENAME gtt
WHERE i.filename=gtt.filename
  AND i.pfw_attempt_id=m.pfw_attempt_id
  AND m.filetype='red_segmap'
  AND i.ccdnum=m.ccdnum
  AND m.filename=fai.filename
  AND fai.archive_name='desar2home'
"""

[Robert-6]
type = "query"
oracle_time = 3.04
doc = "obtain segmentation map images corresponding to the red_immasked images"
query  = """
SELECT i.filename AS redfile,
       fai.filename AS filename,
       fai.path AS PATH,
       fai.compression AS compression,
       m.band AS band,
       m.expnum AS expnum,
       m.ccdnum AS ccdnum
FROM image i,
     miscfile m,
     file_archive_info fai,
     GTT_FILENAME gtt
WHERE i.filename=gtt.filename
  AND i.pfw_attempt_id=m.pfw_attempt_id
  AND m.filetype='red_segmap'
  AND i.ccdnum=m.ccdnum
  AND m.filename=fai.filename
  AND fai.archive_name='desar2home'
"""

[Robert-7]
type="query"
doc = "obtain PSFex models corresponding to the red_immasked images"
query = """
SELECT i.filename AS redfile,
       fai.filename AS filename,
       fai.path AS PATH,
       fai.compression AS compression,
       m.band AS band,
       m.expnum AS expnum,
       m.ccdnum AS ccdnum
FROM image i,
     miscfile m,
     file_archive_info fai,
     GTT_FILENAME gtt
WHERE i.filename=gtt.filename
  AND i.pfw_attempt_id=m.pfw_attempt_id
  AND m.filetype='psfex_model'
  AND i.ccdnum=m.ccdnum
  AND m.filename=fai.filename
  AND fai.archive_name='desar2home'
"""

[Robert-8]
type = "query"
doc = ""
query = """
SELECT i.filename AS redfile,
       fai.filename AS filename,
       fai.path AS PATH,
       fai.compression AS compression,
       m.band  AS band,
       m.expnum AS expnum,
       m.ccdnum AS ccdnum
FROM image i,
     miscfile m,
     file_archive_info fai,
     GTT_FILENAME gtt
WHERE i.filename=gtt.filename
  AND i.pfw_attempt_id=m.pfw_attempt_id
  AND m.filetype='psfex_model'
  AND i.ccdnum=m.ccdnum
  AND m.filename=fai.filename
  AND fai.archive_name='desar2home'
"""

[find-coadds]
type="query"
doc = "How to find a set of coadd images"
ref = "https://opensource.ncsa.illinois.edu/confluence/pages/viewpage.action?spaceKey=DESDM&title=Y6A1+Release+Notes"
query="""
SELECT fai.path, fai.filename, fai.compression
FROM y6a2_proctag t, y6a2_coadd c, y6a2_file_archive_info fai 
WHERE t.tag='Y6A2_COADD' 
    and t.pfw_attempt_id=c.pfw_attempt_id 
    and c.filename=fai.filename 
    and c.band = 'z';
"""

[objects_in_file]
type="query"
doc="How to find FITS tables for  coadd objects for a single-tile:"
ref="https://opensource.ncsa.illinois.edu/confluence/pages/viewpage.action?spaceKey=DESDM&title=Y6A1+Release+Notes"
query="""
SELECT fai.path, fai.filename, fai.compression
FROM y6a2_catalog c, y6a2_file_archive_info fai 
WHERE c.tilename='DES0000+0209'
    and c.filetype='coadd_cat'
    and c.filename=fai.filename;
"""

[se-into-coadd]
type="query"
doc="How to find the single epoch images that went into a tile"
ref="https://opensource.ncsa.illinois.edu/confluence/pages/viewpage.action?spaceKey=DESDM&title=Y6A1+Release+Notes"
query= """
select fai.path,fai.filename
from y6a2_proctag t, y6a2_image i, y6a2_image j, y6a2_file_archive_info fai
where t.tag='Y6A2_COADD'
    and t.pfw_attempt_id=i.pfw_attempt_id
    and i.tilename='DES0000+0209'
    and i.filetype='coadd_nwgint'
    and i.expnum=j.expnum and i.ccdnum=j.ccdnum
    and j.filetype='red_immask'
    and j.filename=fai.filename;
"""


[se-at-specific-ra-dec]
type="query"
doc="How to find the single epoch images that went into a tile"
ref="https://opensource.ncsa.illinois.edu/confluence/pages/viewpage.action?spaceKey=DESDM&title=Y6A1+Release+Notes"
query="""
SELECT fai.path,fai.filename,fai.compression
FROM y6a2_file_archive_info fai, y6a2_image i, y6a2_proctag t
WHERE t.tag='Y6A1_FINALCUT'
    and t.pfw_attempt_id=i.pfw_attempt_id
    and i.filetype='red_immask'
    and i.filename=fai.filename
    and 3.1 between i.racmin and i.racmax
    and -30.4 between i.deccmin and i.deccmax;
"""

[MOF-catalogs]
type="query"
doc="How to obtain the raw MOF and SOF catalogs:"
ref="https://opensource.ncsa.illinois.edu/confluence/pages/viewpage.action?spaceKey=DESDM&title=Y6A1+Release+Notes"
query="""
SELECT fai.path,fai.filename,fai.compression
FROM y6a2_file_archive_info fai, y6a2_miscfile m, y6a2_proctag t
WHERE t.tag='Y6A2_MOF_V1'
    and t.pfw_attempt_id=m.pfw_attempt_id
    and m.filetype='coadd_mof'
    and m.filename=fai.filename
    and m.tilename='DES0000+0209'
"""

