[y6a2_file_archive_info]

columns = [
  ["filename", "TEXT"],
  ["path",     "TEXT"]
  ]
indexes = ["filename"]

select = "SELECT {} from y6a1_file_archive_info ; "
create = "CREATE TABLE IF NOT Exists y6a1_file_archive_info {} ;" 
##########################
[y6a2_proctag]

columns = [
   ["pfw_attempt_id", "INTEGER"],
   ["tag",            "TEXT"]  
   ]
indexes = ["tag", "pfw_attempt_id"]

select = "SELECT {}  from y6a1_proctag;"
create = "CREATE TABLE IF NOT Exists  y6a1_proctag {} ; "
##########################
[y6a2_image]

columns = [
           ["pfw_attempt_id", "INTEGER"],  
           ["filetype",       "TEXT"],
           ["filename",       "TEXT"], 
           ["expnum",         "INTEGER"],
           ["ccdnum",         "INTEGER"],
           ["tilename",       "TEXT"]
          ]
#indexes = ["pfw_attempt_id", "filetype", "filename", "tilename", "expnum", "ccdnum"]
#indexes = ["pfw_attempt_id",  "filename, filetype", "tilename", "expnum, ccdnum"]
indexes = ["pfw_attempt_id",  "tilename, filename, filetype", "expnum, ccdnum"]

select = "SELECT  {} FROM y6a1_image ;"
create = "CREATE TABLE IF NOT EXISTS y6a1_image {} ;"

##########################
[y6a2_exclude_list]

columns = [
   ["expnum", "INTEGER"],
   ["ccdum",  "INTEGER"],
   ["reason", "TEXT"],
   ["analyst,  "TEXT"]
   ]
indexes = []

select = "SELECT {} FROM y6a2_exclude_list ;"
create = "CREATE {} IF NOT EXISTS y6a2_exclude_list {}; commit;"

##########################
#
# use cases
# 
#########################

[uc-se-into-coadd]
doc="How to find the single epoch images that went into a tile"
query= """
select fai.path,fai.filename
from y6a1_proctag t, y6a1_image i, y6a1_image j, y6a1_file_archive_info fai
where t.tag='Y6A1_COADD'
    and t.pfw_attempt_id=i.pfw_attempt_id
    and i.tilename='DES0000+0209'
    and i.filetype='coadd_nwgint'
    and i.expnum=j.expnum and i.ccdnum=j.ccdnum
    and j.filetype='red_immask'
    and j.filename=fai.filename;
"""
