

##########################

[y6a1_proctag]

columns = [
   ["pfw_attempt_id", "INTEGER"],
   ["tag",            "TEXT"]  
   ]
indexes = ["tag", "pwf_attempt_id"]

select = "SELECT {}  from y6a1_proctag;"
create = "CREATE TABLE IF NOT Exists  y6a1_proctag {} ;  commit;"

##########################
[y6a1_image]

columns = [
           ["pfw_attempt_id", "INTEGER"],  
           ["filetype",       "TEXT"],
           ["filename",       "TEXT"], 
           ["expnum",         "INTEGER"],
           ["ccdnum",         "INTEGER"],
           ["tilename",       "TEXT"]
          ]
indexes = ["pfw_attempt_id", "filetype", "filename", "tilename"]

select = "SELECT  {} FROM y6a1_image ;"
create = "CREATE TABLE IF NOT EXISTS y6a1_image {} ; commit;"

##########################
[pfw_attempt_id]

columns = [
   ["tilename",     "TEXT"],
   ["coadd_nwgint", "TEXT"],
   ["expnum",       "INTEGER"],
   ["ccdnum",       "INTEGER"]
   ]
indexes = ["tilename", "expnum", "ccdnum"]

select = "SELECT {} FROM pfw_attempt_id ;"
create = "CREATE {} IF NOT EXISTS pfw_attempt_id {}; commit;"

##########################
[y6a1_file_archive_info]

columns = [
  ["filetype", "TEXT"],
  ["ccdnum",   "INTEGER"],
  ["tag",      "TEXT"]
  ]
indexes = ["ccdnum", "filetype", "tag"]

select = "SELECT {} from y6a1_file_archive_info ; "
create = "CREATE TABLE IF NOT Exists y6a1_file_archive_info {} ; commit ;" 

